[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.snmp]]
  agents = ["udp://snmp-simulator:161"]
  version = 2
  community = "public"
  interval = "60s"

  [[inputs.snmp.field]]
    name = "node"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = ["node"]

    [[inputs.snmp.table.field]]
      name = "intf"
      oid = ".1.3.6.1.2.1.2.2.1.2"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "rx_bytes"
      oid = ".1.3.6.1.2.1.2.2.1.10"

    [[inputs.snmp.table.field]]
      name = "tx_bytes"
      oid = ".1.3.6.1.2.1.2.2.1.16"

    [[inputs.snmp.table.field]]
      name = "oper_status"
      oid = ".1.3.6.1.2.1.2.2.1.8"


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.kafka]]
  brokers = ["kafka:9092"]
  topic = "snmp.telegraf.metrics"
  data_format = "json"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
