[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.clickhouse]]
  ## ClickHouse server address
  servers = ["tcp://clickhouse:9000"]
  database = "metranova"
  username = "default"
  password = ""

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["metrics"]
  consumer_group = "telegraf"
  offset = "oldest"
  data_format = "influx"

[[inputs.snmp]]
  agents = ["udp://snmp-simulator:161"]
  version = 2
  community = "public"
  interval = "60s"

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "1.3.6.1.2.1.1.3.0"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "ifTable"
    inherit_tags = ["hostname"]

    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "ifInOctets"
      oid = "IF-MIB::ifInOctets"

    [[inputs.snmp.table.field]]
      name = "ifOutOctets"
      oid = "IF-MIB::ifOutOctets"

    [[inputs.snmp.table.field]]
      name = "ifOperStatus"
      oid = "IF-MIB::ifOperStatus"
